# -*- coding: utf-8 -*-
"""bj1059.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r-0fUzEUodagxp7BcMBcaAySTZqhuOjv
"""

L = int(input())
idx = 0
s = list(map(int, input().split()))
s = sorted(s)
k = int(input())

if len(s) == 1:
    if s[0] == k:
        print(0)
    else:
        sol = (k - 1) * (s[0]- k - 1) + (k - 1) + (s[0]- k - 1)
        print(sol)

else:
    for i in range(L):
        if k == s[i]:
            print(0)
            break
        else:
            if k < s[i]:
                if i == 0:
                    sol = (k - 1) * (s[0]- k - 1) + (k - 1) + (s[0]- k - 1)
                    print(sol)
                    break


                else:
                    idx = i-1
                    sol = (k - s[idx] - 1) * (s[idx+1]- k - 1) + (k - s[idx] - 1) + (s[idx+1]- k - 1)
                    print(sol)
                    break

# 이상현꺼

L = int(input())
nums = list(map(int, input().split()))
n = int(input())
nums.sort()
if n in nums:
    print(0)
else:
    if len(nums) == 1:
        nums = [0,nums[0]]
    for i in range(len(nums)):
        if n < nums[i]:
            if i == 0:
                idx = -1
                break
            idx = i-1
            break

    if nums[idx+1]-1 <= nums[idx]+1:
        print(0)
    else:
        sum = 0
        for i in range(nums[idx]+1, n+1):
            if i < n:
                sum += (nums[idx+1]-n)
            else:
                sum += (nums[idx+1]-n-1)
        print(sum)