# -*- coding: utf-8 -*-
"""bj10867.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18MeEww7sKb-fyeGdOYI1VEiets-qaVuJ
"""

# no.10867

N = int(input())

L = map(int, input().split())

L = set(L)
L = list(L)
L.sort()

for x in L:
    print(x, end=' ')

