# -*- coding: utf-8 -*-
"""bj10814.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16vRVd95tVoPB6_wfZOjJejV113wk80Nn
"""

# no.10814

N = int(input())
L = []

for i in range(N):
    o, n = input().split()
    o = int(o)

    L.append([o, n])

L = sorted(L, key = lambda x: x[0])

for i in range(N):
    print(L[i][0], L[i][1])