# -*- coding: utf-8 -*-
"""bj11098.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1skQzWAGSTTH9EJhz7wA8cefODBLtVpwj
"""

# no.11098

N = int(input())

for _ in range(N):
    p = int(input())
    n = -1
    for _ in range(p):
        a, b = input().split()
        a = int(a)

        if a > n:
            sol = b
            n = a
        else:
            continue
    print(sol)

