# -*- coding: utf-8 -*-
"""bj1181.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DE80LSE9EiEXkZpgr7b-5YhfljxS1rrF
"""

# no.1181

N = int(input())
L = []

for _ in range(N):
    tmp = input()
    if tmp in L:
        continue
    L.append(tmp)

L.sort(key=len)
ll = [L[0]]

for i in range(len(L) - 1):
    if len(L[i]) == len(L[i+1]):
        ll.append(L[i+1])
    else:
        ll.sort()
        for x in ll:
            print(x)
        ll = [L[i+1]]

if ll:
    for x in ll:
        print(x)

# 2차 시도
N = int(input())

L = []
for _ in range(N):
    k = input()
    L.append(k)

L = set(L)
L = list(L)

L.sort(key=len)

l = [L[0]]
for i in range(1,len(L)):
    if len(L[i-1]) == len(L[i]):
        l.append(L[i])
    else:
        l.sort()
        for x in l:
            print(x)
        l = [L[i]]

if l:
    l.sort()
    for x in l:
        print(x)