# -*- coding: utf-8 -*-
"""bj11720.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UtgqhMCgp2bUS06JOF36p3nxr_AKSFK3
"""

# no.11720

N = int(input())
n = input()
sol = 0

for x in n:
    sol += int(x)

print(sol)