# -*- coding: utf-8 -*-
"""bj1316.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1twKCJSQIDnGzstBpqeyt-mNpL99m87Fi
"""

# no.1316

N = int(input())

strl = []
cnt = 0

for _ in range(N):
    st = input()
    strl.append(st)

for x in strl:
    L = [x[0]]
    for i in range(1, len(x)):
        if x[i-1] == x[i]:
            continue
        else:
            if x[i] in L:
                cnt += 1
                break
            else:
                L.append(x[i])

print(len(strl)-cnt)

for i in range(10):
    print(i)
    for j in range(5):
        if j == 2:
            print('다음')
            break
            
        else:
            print(j)