# -*- coding: utf-8 -*-
"""bj1427.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SEJrkZ2PuX32QkhcicAIcnBs8AJd8NgD
"""

# no.1416

num = int(input())
num = str(num)
numl = list(''.join(num))
numl = sorted(numl, reverse=True)


print(int(''.join(numl)))

num = 123456
num = str(num)
numl = list(''.join(num))
numl = sorted(numl, reverse=True)

print(numl)

print(''.join(numl))