# -*- coding: utf-8 -*-
"""bj15652.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RD20Tnv1mu5Eqz67T_kAMLCAN90h_F3M
"""

# no.15652 
# N과 M(4)

from itertools import combinations_with_replacement

N, M = map(int, input().split())

for x in combinations_with_replacement(range(1, N+1), M):
    for j in x:
        print(j, end=" ")
    print()

from itertools import combinations_with_replacement

n, m = 3, 2

list(combinations_with_replacement(range(3), m))

# no.15650

from itertools import combinations

N, M = map(int, input().split())

for x in combinations(range(1, N+1), M):
    for j in x:
        print(j, end=" ")
    print()

# no.15651

from itertools import product

N, M = map(int, input().split())

for x in product(range(1, N+1), repeat=M):
    for j in x:
        print(j, end=" ")
    print()