# -*- coding: utf-8 -*-
"""bj17219.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r3H1-F_BuAi4CRexLKYDRDGkdBQZY7bF
"""

# no.17219

N, M = map(int, input().split())

my = {}
for i in range(N):
    k, v = input().split()
    my[k] = v

for i in range(M):
    ke = input()
    print(my[ke])