# -*- coding: utf-8 -*-
"""bj23056.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XVoKfxulgcF52Vs5rKZTHsczvFC6lss_
"""

# no.23056
N, M = map(int, input().split())
L = [[] for i in range(N)]

while 1:
    n, name = input().split()
    n = int(n)
    if n == 0:
        break
    if len(L[n-1]) == M:
        continue
    L[n-1].append(name)


for i in range(N):
    L[i].sort()
    L[i].sort(key=len)

for i in range(0, N, 2):
    if L[i]:
        for x in L[i]:
            print(i+1, x)

for i in range(1, N, 2):
    if L[i]:
        for x in L[i]:
            print(i+1, x)

L = [['minjun'], ['junkyu', 'dohyun'] ,['sunyoung', 'kihyun'], ['hyunsu']]


for i in range(N):
    L[i].sort()
    L[i].sort(key=len)

for i in range(0, N, 2):
    if L[i]:
        for x in L[i]:
            print(i+1, x)

for i in range(1, N, 2):
    if L[i]:
        for x in L[i]:
            print(i+1, x)

a = ['123', '122314',  'bs','as']
b = sorted(a, key = lambda (len, x))
print(a)