# -*- coding: utf-8 -*-
"""bj2750.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mhvaENG-SfXAo75xGSJ7QkYyhPxkrSWf
"""

# no.2750

N = int(input())

L = []

for i in range(N):
    L.append(int(input()))

L.sort()

for x in L:
    print(x)

