# -*- coding: utf-8 -*-
"""bj2740ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1snKH0xoPi5zbcJnIQNFYFka1R5B05nyh
"""

# no.2740

n, m = map(int, input().split())

mat1 = []
mat2 = []

for i in range(n):
    tmp = list(map(int, input().split()))
    mat1.append(tmp)

m, k = map(int, input().split())

for i in range(m):
    tmp = list(map(float, input().split()))
    mat2.append(tmp)

for i in range(n):
    for j in range(k):
        sum = 0
        for z in range(m):
            sum += mat1[i][z] * mat2[z][j]
        print(int(sum), end=" ")
    print()

int(-1)