# -*- coding: utf-8 -*-
"""bj2839.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TPErm9g7iVjCumZp9dTRy6h02pYqPpqV
"""

# no.2839

N = int(input())

five = N // 5

while 1:
    thr = (N - five*5) // 3
    n = five*5 + thr*3

    if n == N:
        print(five + thr)
        break
    if five == 0 and n != N:
        print(-1)
        break

    five -= 1