# -*- coding: utf-8 -*-
"""bj5052.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vYXSqaNCFEJqVFU4lCE7QJniUR19oAHP
"""

# no.5052

t = int(input())

for _ in range(t):
    n = int(input())
    L = []
    sol = 'YES'

    for _ in range(n):
        pn = input()
        L.append(pn)

    L.sort()

    for i in range(n-1):
        l1 = len(L[i])
        l2 = len(L[i+1])

        if l1 <= l2:
            if L[i] == L[i+1][:l1]:
                sol = 'NO'
                break
        else:
            if L[i][:l2] == L[i+1]:
                sol = 'NO'
                break


    print(sol)

a = '123'
b = '5612309'


l = [a, b]

b[:3]