# -*- coding: utf-8 -*-
"""bj_function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cWW8Nr69eYQNRVOAhu4VvETyPqCBA1aE
"""

# 15596

def solve(a):
    sol = sum(a)
    return sol

# 1065
n = int(input())

cash = [1] * 99

for i in range(100, 1000):
    n3 = i // 100
    n2 = i //10 - n3*10
    n1 = i % 10

    if n3 - n2 == n2 - n1:
        cash.append(1)
    else:
        cash.append(0)

cash.append(0)

L = cash[:n]
print(sum(L))

i  = 123

n3 = i // 100
n2 = i //10 - n3*10
n1 = i % 10

print(n1, n2, n3)